[package]
name = "rust-shopping-bot"
version = "0.1.0"
authors = ["Roman Fro≈Çow <rofrol@gmail.com>"]

[dependencies]
actix-web = "1.0.0-beta.5"
env_logger = "0.6.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
bytes = "0.4.12"
futures = "0.1.27"
